@extends('layouts.admin')
@section('title', __('Scheduler and backups'))
@section('content')
<div class="pagehead"><h1>{{ __('Scheduler and backups') }}</h1></div>
<div class="panel"><div class="panel-hd"><h3>{{ __('Web scheduler fallback') }}</h3></div><div class="panel-bd">
<p>{{ __('Enable only when your hosting cannot run the normal scheduler. Requests need the private PHAROS_WEB_CRON_TOKEN environment credential in an Authorization: Bearer header.') }}</p><p><code>POST {{ url('/api/cron') }}</code><br><code>GET {{ url('/cron/run') }}</code></p><p>{{ __('External scheduler services can call the GET address with an Authorization: Bearer header. Credentials in query strings are rejected to keep them out of access logs.') }}</p>
<p>{{ $cronConfigured ? __('Credential configured') : __('Credential not configured') }}</p><form method="post" action="{{ route('admin.system-monitoring.cron') }}">@csrf @method('PUT')<input type="hidden" name="enabled" value="0"><label class="check"><input type="checkbox" name="enabled" value="1" @checked($webEnabled)>{{ __('Enable web scheduler') }}</label><button class="btn">{{ __('Save') }}</button></form></div></div>
<div class="panel"><div class="panel-hd"><h3>{{ __('Remote backups') }}</h3></div><div class="panel-bd"><p>{{ __('Daily backups include a consistent database snapshot, application files, environment and uploaded files. Destinations receive private archives and each upload is downloaded to verify its checksum. Keep remote storage private.') }}</p>
@foreach ($destinations as $d)<div><strong>{{ $d->name }} · {{ strtoupper($d->driver) }}</strong><p>{{ __('Last success') }}: {{ $d->last_success_at?->diffForHumans()??__('Never') }} @if ($d->last_error) · {{ $d->last_error }}@endif</p><form method="post" action="{{ route('admin.backup-destinations.run',$d) }}">@csrf <button class="btn">{{ __('Back up now') }}</button></form><form method="post" action="{{ route('admin.backup-destinations.destroy',$d) }}">@csrf @method('DELETE')<button class="btn danger">{{ __('Remove destination') }}</button></form></div>@endforeach
@foreach (['s3'=>__('S3 destination'),'sftp'=>__('SFTP destination')] as $driver=>$label)<details><summary>{{ __($label) }}</summary><form method="post" action="{{ route('admin.backup-destinations.store') }}">@csrf<input type="hidden" name="driver" value="{{ $driver }}"><label>{{ __('Name') }}<input name="name" maxlength="100" required></label>
@if ($driver==='s3')<label>{{ __('HTTPS endpoint (optional for AWS)') }}<input name="endpoint" type="url"></label><label>{{ __('Region') }}<input name="region" value="us-east-1" required></label><label>{{ __('Bucket') }}<input name="bucket" required></label><label>{{ __('Folder prefix') }}<input name="prefix"></label><label>{{ __('Access key') }}<input name="key" autocomplete="off" required></label><label>{{ __('Secret key') }}<input name="secret" type="password" autocomplete="new-password" required></label>
@else<label>{{ __('Host') }}<input name="host" required></label><label>{{ __('Port') }}<input name="port" type="number" value="22" min="1" max="65535"></label><label>{{ __('Username') }}<input name="username" required></label><label>{{ __('Password') }}<input name="password" type="password" autocomplete="new-password" required></label><label>{{ __('Verified server host fingerprint') }}<input name="fingerprint" required></label><label>{{ __('Remote directory') }}<input name="root" value="/backups" required></label>@endif
<label class="check"><input name="allow_private" type="checkbox" value="1">{{ __('Allow this destination on a private network') }}</label><button class="btn">{{ __('Add destination') }}</button></form></details>@endforeach
</div></div>
@endsection
